apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omdb-landing
  namespace: kinopoisk
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: "openmovieapi.dev"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: omdb-landing
                port:
                  number: 8080
